const productDetails =  [
      { "id":"1",
        "productName": "MEN'S BETTER THAN NAKED™ JACKET",
        "productImageUrl": "http://images.thenorthface.com/is/image/TheNorthFace/236x204_CLR/mens-better-than-naked-jacket-AVMH_LC9_hero.png",
        "type_of_product": "Men's",
        "price":"100",
        "quantity":"1",
      },
      { "id":"2",
        "productName": "WOMEN'S BETTER THAN NAKED™ JACKET",
        "productImageUrl": "http://images.thenorthface.com/is/image/TheNorthFace/236x204_CLR/womens-better-than-naked-jacket-AVKL_NN4_hero.png",
        "type_of_product": "Women's",
        "price":"200",
        "quantity":"1",
      },
      { "id":"3",
        "productName": "WOMEN'S SINGLE-TRACK SHOE",
        "productImageUrl": "http://images.thenorthface.com/is/image/TheNorthFace/236x204_CLR/womens-single-track-shoe-ALQF_JM3_hero.png",
        "type_of_product": "Running Shoes",
        "price":"300",
        "quantity":"1",
      },
      { "id":"4",
        "productName": "Enduro Boa® Hydration Pack",
        "productImageUrl": "http://images.thenorthface.com/is/image/TheNorthFace/236x204_CLR/enduro-boa-hydration-pack-AJQZ_JK3_hero.png",
        "type_of_product": "Equipment",
        "price":"400",
        "quantity":"1",
      }
    ,
      { "id":"5",
        "productName": "MEN'S BETTER THAN NAKED™ JACKET PR2",
        "productImageUrl": "http://images.thenorthface.com/is/image/TheNorthFace/236x204_CLR/mens-better-than-naked-jacket-AVMH_LC9_hero.png",
        "type_of_product": "Men's",
        "price":"500",
        "quantity":"1",
      },
      { "id":"6",
        "productName": "WOMEN'S BETTER THAN NAKED™ JACKET PR2",
        "productImageUrl": "http://images.thenorthface.com/is/image/TheNorthFace/236x204_CLR/womens-better-than-naked-jacket-AVKL_NN4_hero.png",
        "type_of_product": "Women's",
        "price":"600",
        "quantity":"1",
      },
      { "id":"7",
        "productName": "WOMEN'S SINGLE-TRACK SHOE PR2",
        "productImageUrl": "http://images.thenorthface.com/is/image/TheNorthFace/236x204_CLR/womens-single-track-shoe-ALQF_JM3_hero.png",
        "type_of_product": "Running Shoes",
        "price":"700",
        "quantity":"1",
      },
      { "id":"8",
        "productName": "Enduro Boa® Hydration Pack PR2",
        "productImageUrl": "http://images.thenorthface.com/is/image/TheNorthFace/236x204_CLR/enduro-boa-hydration-pack-AJQZ_JK3_hero.png",
        "type_of_product": "Equipment",
        "price":"900",
        "quantity":"1",
      }
    ];
  
export default productDetails;
  